name: 'Push Validation'

on: 
  push:
    branches:
      - master

jobs:
  CommonvSphereTasks-module:
    name: CommonvSphereTasks Module Tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester Module
      run: .\.github\workflows\Install-PesterModule.ps1
      shell: pwsh
    - name: Run Pester Tests
      run: .\.github\workflows\Invoke-PesterTests.ps1
      shell: pwsh